sudo: required
language: node_js
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project multi-k8s-394002
  - gcloud config set compute/zone asia-southeast1-b
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # - docker build -t pranavbhosale25/react-test -f ./client/Dockerfile.dev ./client // build test version
  - echo "before install completed"

script:
  - echo "script section completed"
  # - docker run -e CI=true pranavbhosale25/react-test npm test

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master